version: '3'
services:
  server:
    build:
      context: .
      args:
        API_HOST: http://server:4000
    env_file: .env
    ports:
      - 8080:4000
    links:
      - mongodb
      - selenium # For demo only. Wouldnt normally make the app dependant on the selenium container
  mongodb:
    image: mongo
  selenium:
    image: selenium/standalone-chrome-debug:latest
    environment:
      - VNC_NO_PASSWORD=1
    ports:
      - 4444 # Selenium server
      - 5900:5900 # VNC server bound to port 5900. Please make sure your localhost's 5900 is available.
