version: '3'
services:
  server:
    build:
      context: .
      args:
        API_HOST: http://localhost:8080
    environment:
      FRONTEND_HOST: http://localhost:8080
      APP_PORT: 4000
      DB_HOST: mongodb
      DB_NAME: todos
    ports:
      - 8080:4000
    links:
      - mongodb
  mongodb:
    image: mongo
